= Red Hat AI on AWS Cloud
:navtitle: Home

=== Example Use-case

Your customer reaches out because they are beginning a new generative AI project and want to know how you help?

They are already an AWS customer but are looking for an alterntive way to deploy AI models without needing data scientist or MLOps engineers, instead this team of developeers and IT operations will be leading this project.   The team needs a new chatbot service for their call center that can provide internal only support calls


== Introduction

This course is intendted Red Hat Technical Sales, Solution Architects, Support and Services team members who are discussing Red Hat AI platform solutions with customers who utilize Cloud Services or have the flexibility to use cloud services to provision such environments.

Waiting for hardware can take weeks or months, which is why obtaining an Red Hat AI Platforms from Cloud provider, AWS specifically in this course, in minutes can be a crucial component for unlocking the full potential of *Generative AI* or *Predictive AI* for organizations on the move.

Utilizing on-demand cloud resources to evaluate models can avoid purchasing high-cost GPUs used for model training and inferencing, instead using on what is needed and shutting down reserach and deployment projects.

This course will focus only on Red Hat AI solutions that can be instantiated on the AWS Cloud Provider.

For those not familiar with the Red Hat AI Platform, it  is made up of Red Hat Enterprise Linux AI ( RHEL AI ) and Red Hat OpenShift AI ( RHOAI ).

RHEL AI is targeted towards customers who are looking for a Generative AI fine tuning and model inferencing platform that can be run across cloud hyperscales and on premises providing a hybrid cloud experience utilzing a single platform for engineers and operations.

RHOAI - is fully scallable Machine Learning Opeations Platform( MLOps ) plaform that provides the ability to automate Data collection, processing and prepartion. Then automate model experimentation, training, and versioning, and finally serving models securely, and providing the infrastructue to run AI applciations.


== Objectives

==== On completing this course, you should be able to:

  * Describe how AWS Cloud Deployment can simplify Red Hat AI Adoption
  * Understand how to Deploy Red Hat AI Solutions on AWS
  * Identify the difference between Red Hat AI Platform and AWS SaaS offerings
  * Explain the value / benefits of RHOAI cloud services
  * Identify Red Hat’s AI platforms that comprise Red Hat AI that can run on AWS
  * Explain how to deploy RHEL AI on AWS. 
  * Explain the customer challenges that RHOAI Cloud Service can address.
  * Hands on Activities - Getting hands on with AWS AI Services
  * Hands on Activities - External Lab- Deploy Red Hat AI on AWS
  * Hands on Activities - Rosa Hands on Lab

=== 

Contributors
The PTL team acknowledges the valuable contributions of the following Red Hat associates:

Karlos Knox

== Classroom Environment

Launch an https://demo.redhat.com/catalog?search=AWS+Blank+Open+Environment&item=babylon-catalog-prod%2Fsandboxes-gpte.sandbox-open.prod[AWS Blank Open Environment, window=blank] to follow along with this guided lab.


