= Red Hat AI on AWS Cloud
:navtitle: Home

== Introduction

This course provides a comprehensive understanding of how to deploy Red Hat AI's OpenShift AI and RHEL AI products on Amazon Web Services (AWS). It prioritizes Red Hat managed offerings but includes self-managed configurations when no managed service is available. 

In addition, this course introduces various AWS AI services including Amazon SageMaker, Amazon Bedrock, Amazon Q, and Amazon Elastic Cloud Compute (EC2) instances to help learners understand how these services complement and compete Red Hat AI.

By the end of this course, learners will have a solid foundation in deploying and integrating Red Hat AI with various AWS AI Services. They will understand how to choose the right deployment model and services based on their specific use case and requirements. 

The course includes several sections that reference external labs where practical skills may be needed. However, it is currently missing a specific lab component showcasing the interaction between Red Hat AI and AWS AI Services in a hybrid deployment scenario. This lab will be added to provide learners with hands-on experience in deploying and managing Red Hat AI on AWS using managed offerings while integrating with AWS AI services.


== Objectives

* Understand the Red Hat AI Platform comprised of OpenShift AI and RHEL AI.
* Knowledge of configuring AWS to host for Red Hat AI workloads.
* Describe the benefits of Red Hat OpenShift AI Cloud Service.
* Understand design decisions for self-managed deployment of RHEL AI on AWS. (managed offering coming soon)
* Knowledge of AWS AI Services: Amazon SageMaker, Amazon Bedrock, Amazon Q, and EC2 instances.
* Evaluate the differences between Red Hat AI and (AWS) AI offerings.
* Hands-on labs (to be added) to reinforce practical skills in deploying and managing Red Hat AI integration with AWS AI Services.

 

=== Contributors
The PTL team acknowledges the valuable contributions of the following Red Hat associates:

Karlos Knox


== Classroom Environment

Recommended starting the lab now so it's available when you reach the AWS segment of the course.

Launch an https://demo.redhat.com/catalog?search=AWS+Blank+Open+Environment&item=babylon-catalog-prod%2Fsandboxes-gpte.sandbox-open.prod[AWS Blank Open Environment, window=blank] to follow along with this guided lab.



