= AWS AI Services

This section provides an overview of the AI / ML services available natively from AWS.
The goal of this section is to showcase the products and capabilities in order to understand how these features can be recreated within or used adjacently to OpenShift AI for customer use cases.

For more details on these services you can use the links below.

 * https://aws.amazon.com/ai/generative-ai/services/[AWS AI Website, window=blank]

 * https://docs.aws.amazon.com/whitepapers/latest/aws-caf-for-ai/aws-caf-for-ai.html[AWS Cloud Adoption FrameWork, window=blank] for Artificial Intelligence, Machine Learning, and Generative AI

AWS boasts a comprehensive range of services, from plug-and-play AI services, to customizable models via AWS SageMaker. Users can leverage Amazon Bedrock, the easiest way to build and scale generative AI with foundation models in the cloud, to power their applications all without writing any code. Lastly, a vast network of AWS-certified partners are available to help customers drive innovation with AI/ML, offering top-tier services to fit every budget.

Lets take a tour of AWS AI services and instances. 



