= Section 1

=== AWS MarketPlace Product Overview - Red Hat OpenShift AI

Red Hat OpenShift AI enables companies to solve critical business challenges by providing a fully managed cloud service environment based-on the Red Hat OpenShift Service on AWS. Red Hat OpenShift AI allows organizations to quickly build and deploy artificial intelligence (AI)/ML models by integrating open-source applications with commercial partner technology.


Red Hat OpenShift AI is an easy-to-configure cloud service that provides a powerful platform for building AI/ML models and applications. It combines the self-service data scientists and developers want with the confidence enterprise IT demands into one common platform. Common tooling, such as Jupyter notebooks and associated TensorFlow and Pytorch frameworks, are an add-on to Red Hat OpenShift Service on AWS, an application platform cloud service powered by Kubernetes and co-managed by Red Hat and Amazon.


=== Rosa Cluster Deployment - CLI

Deploy ROSA cluster
set some environment variables


 Copy
  export ROSA_CLUSTER_NAME=mycluster
  export AWS_ACCOUNT_ID=`aws sts get-caller-identity \
    --query Account --output text`
  export REGION=us-east-2
  export AWS_PAGER=""

Make you your ROSA CLI version is correct (v1.2.25 or higher)


 Copy
  rosa version

Run the rosa cli to create your cluster

Note there are many configurable installation options that you can view using rosa create cluster -h. The following will create a cluster with all of the default options.


Copy
 rosa create cluster --sts --cluster-name ${ROSA_CLUSTER_NAME} \
   --region ${REGION} --mode auto --yes

Watch the install logs


Copy
 rosa logs install -c $ROSA_CLUSTER_NAME --watch --tail 10

Validate the cluster
Once the cluster has finished installing we can validate we can access it

Create an Admin user


Copy
 rosa create admin -c $ROSA_CLUSTER_NAME

Wait a few moments and run the oc login command it provides. If it fails, or if you get a warning about TLS certificates, wait a few minutes and try again.

Run oc whoami --show-console, browse to the provided URL and log in using the credentials provided above.

Cleanup
 Delete the ROSA cluster


 rosa delete cluster -c $ROSA_CLUSTER_NAME
 Clean up the STS roles

Once the cluster has been deleted we can delete the STS roles.

Tip You can get the correct commands with the ID filled in from the output of the previous step.



 rosa delete operator-roles -c <id> --yes --mode auto
 rosa delete oidc-provider -c <id>  --yes --mode auto


 https://console.redhat.com/openshift/overview/rosa/hands-on?source=rhhe7&intcmp=7015Y000003sdOhQAI

 https://www.redhat.com/en/products/interactive-walkthrough/install-rosa


OpenShift AI is available as an add-on cloud service to Red Hat OpenShift Service on AWS or Red Hat OpenShift Dedicated or as a self-managed software product. It provides an AI platform with popular open source tooling. Familiar tools and libraries like Jupyter, TensorFlow, and PyTorch along with MLOps components for model serving and data science pipelines are integrated into a flexible UI.


