= Azure AI Services


https://azure.microsoft.com/en-us/products/ai-services/[Azure AI Service Homepage, window=blank]

=== Azure Open AI Service

Develop generative AI experiences with a diverse set of models from OpenAI, Meta, and beyond. Begin building.

Azure OpenAI Service provides access to many cutting edge models including GPT-3.5-Turbo, GPT-4 and DALL-E, Whisper, Babbage and Davinci.

Conversational AI
AI-generated bots, questions and answers, and contact center solutions to streamline and improve customer service.

Content creation
AI tools such as GPT-4 and DALL·E for creative ideation, design, and content writing.

Data grounding
Ability to run models on your data for greater accuracy and insights with Azure OpenAI Service on your data.

https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models

== Azure AI Studio

Develop and deploy generative AI apps and APIs responsibly with a comprehensive platform


AI Studio is intended for professional software developers including cloud architects and technical decision-makers who want to create generative AI applications and custom copilot experiences.


Yes. Azure AI Studio includes a robust and growing catalog of frontier and open-source models that can be applied over your data from Microsoft, OpenAI, Hugging Face, Meta, Cohere, and other partners. You can even compare models by task using open-source datasets and evaluate the model with your own test data to see how the pretrained model would perform to fit your own use case.




=== Azure AI Search

Azure AI Search is a platform as a service that helps developers create their own cloud search solutions.

Deliver high-quality responses with a vector database built for advanced retrieval augmented generation (RAG) and modern search

Focus on exponential growth with an enterprise-ready vector database that comes with security, compliance, and responsible AI practices built in.



=== Aure AI Content Safety

Detect and block violence, hate, sexual, and self-harm content. Configure severity thresholds for your specific use case, and adhere to your responsible AI policies.

Create unique content filters tailored to your requirements using custom categories. Quickly train a new custom category by providing examples of content you need to block.

Safeguard your AI applications against prompt injection attacks and jailbreak attempts. Identify and mitigate both direct and indirect threats with prompt shields.

Identify and correct generative AI hallucinations and ensure outputs are reliable, accurate, and grounded in data with groundedness detection.

Pinpoint copyrighted content and provide sources for preexisting text and code with protected material detection.

=== Azure AI Vision

Azure AI Vision is a unified service that offers innovative computer vision capabilities. Give your apps the ability to analyze images, read text, and detect faces with prebuilt image tagging, text extraction with optical character recognition (OCR), and responsible facial recognition. Incorporate vision features into your projects with no machine learning experience required.

Image analysis
Image analysis that pulls from more than 10,000 concepts and objects to detect, classify, caption, and generate insights.

Spatial analysis
Spatial analysis to understand people's presence and movements within physical areas in real time.

Optical character recognition (OCR)
Optical character recognition (OCR) to extract printed and handwritten text from images with varied languages and writing styles.

Facial recognition
Facial recognition to create intelligent applications that recognize and verify human identity.




https://azure.microsoft.com/en-us/blog/introducing-phi-3-redefining-whats-possible-with-slms/[PHI Small Language Model, window=blank]

he blog post introduces Phi-3, a family of open AI models by Microsoft, designed to redefine what is possible with small language models (SLMs). Phi-3 models are the most compatable and cost-effective SLMs, outperforming models of the same size and even larger ones in language, reasoning, coding, and math benchmarks. The Phi-3-mini model, with 3.8 billion parameters, is available on Microsoft Azure AI Studio, Hugging Face, and Ollama, supporting context windows for up to 128K tokens. These models are optimized for various hardware, including NVIDIA NIM microservices. Additional models, Phi-3-small (7B) and Phi-3-medium (14B), will be available soon.


