= Lab Env RHOAI self-managed

These environments are provided via the Red Hat Demo Platform (RHDP) and run on Cloud Providers but are short term environments that you can deploy for general OpenShift AI development or demo environments.  

These are more effective than using the Cloud Provider directly as the lab environments are automatically cost controlled via auto-shutdown and auto-delete policies reducing the chance that a Cloud Provider or random services are left running in an open account generating possibly high cost.


== Practice Installing OpenShift AI

Hands-on exposure using the OpenShift Dashbaord to deploy OpenShift AI using operators is an essential part of understanding the components that make up OpenShift AI and the "required" operators that enable additional capabilities within OpenShift AI.

These Operators are the minimum required for the self-managed clusters that enable full features (external access) of single and multi-model serving. 

 * Use OpenShift Operator Hub to install operators
 ** Red Hat OpenShift Serverless Operator
 ** Red Hat OpenShift Service Mesh Operator
 ** Red Hat Authorino (Technical Preview) Operator
 ** Red Hat OpenShift AI Operator
 *** Create OpenShift AI Data Science Cluster


