= Appendix

FIXME: Content for Appendix...


https://proceedings.neurips.cc/paper_files/paper/2015/file/86df7dcfd896fcaf2674f757a2463eba-Paper.pdf[hidden technical debt in machine learning]

== AWS ROSA

https://cloud.redhat.com/learn/red-hat-openshift-service-aws-rosa-explained[Red Hat OpenShift Service on AWS (ROSA) explained]

https://www.redhat.com/en/technologies/cloud-computing/openshift/aws/learn#integrate-rosa-with-other-services[Integrating ROSA with other services]

https://www.rosaworkshop.io/rosa/15-sts_explained/[ROSA with AWS STS Explained]

https://www.redhat.com/en/products/interactive-walkthrough/install-rosa[Interactive walkthrough Red Hat OpenShift Service on AWS (ROSA)]

== Microsoft ARO

https://microsoft.github.io/aroworkshop/[Azure Red Hat OpenShift Workshop]

video::Hc8emNr2igU[youtube, width=400]

ROSA in this Course focuses on the  *ROSA with HCP* deployment as the option of choice. However, the other options are listed as they might meet the needs of particular customer. 

[NOTE]
_A somewhat surprising hit at a recent onsite was our discussion of deploying OpenShift using Hosted Control Planes. It turns out that none of the customers in attendance knew about this deployment option. Therefore we spent quite some time explaining how this works and the benefits (densification, cost reduction, deployment speed) of this approach._