= Appendix

== AWS ROSA

=== https://cloud.redhat.com/learn/red-hat-openshift-service-aws-rosa-explained[Red Hat OpenShift Service on AWS (ROSA) explained, window=blank]

This learning path features a series of videos exploring high-level concepts within Red Hat OpenShift Service on Amazon Web Services ROSA and its applications for various business scenarios. Follow principal solutions architect Ryan Niksch and several Red Hat OpenShift experts as they discuss specific use cases, detailed deep dives, and specialized strategies to get the most out of ROSA. 

'''

Explore learning materials and tools designed to help you use Red Hat OpenShift Service on AWS (ROSA), organized by the tasks you need to accomplish:

 * https://www.redhat.com/en/technologies/cloud-computing/openshift/aws/learn#deploy-a-rosa-cluster[Deploy a ROSA cluster, window=blank]

 * https://www.redhat.com/en/technologies/cloud-computing/openshift/aws/learn#configure-and-manage-rosa-clusters[Configure and manage ROSA clusters, window=blank]

 * https://www.redhat.com/en/technologies/cloud-computing/openshift/aws/learn#deploy-workloads-to-rosa-clusters[Deploy workloads to ROSA clusters, window=blank]

  *  https://www.redhat.com/en/technologies/cloud-computing/openshift/aws/learn#integrate-rosa-with-other-services[Integrating ROSA with other services, window=blank]

  * https://www.redhat.com/en/technologies/cloud-computing/openshift/aws/learn#troubleshoot-rosa[Troubleshoot ROSA, window=blank]


'''


https://www.rosaworkshop.io/rosa/15-sts_explained/[ROSA with AWS STS Explained]

These pages are split into three sections.

 . One contains the steps to getting started on ROSA ("Getting started with ROSA").
 . Another is about deploying an application to ROSA to get better familiar with the internals of OpenShift ("Deploy the application").
 . Lastly, some reference pages with a summary of a few key OpenShift concepts that will be used in the workshop, an FAQ, and an explanation of ROSA with STS.

'''

https://www.redhat.com/en/products/interactive-walkthrough/install-rosa[Interactive walkthrough Red Hat OpenShift Service on AWS (ROSA)]


