= Red Hat AI Overview

== Objectives

 * Identify Red Hat’s AI platforms that comprise Red Hat AI.
 * Understand when Openshift AI and RHEL AI products solutions are applicable.


== Red Hat AI Platform


==== For those new to Red Hat AI Platform, let's break down the subscription offerings:

Red Hat AI platform consists of two main components: RHEL AI and OpenShift AI. Currently, these solutions are being integrated to provide a seamless experience.

RHEL AI is a standalone product that can be installed and used independently. If you prefer, it's also included as part of an RHOAI (Red Hat OpenShift AI) subscription.

OpenShift AI provides additional feature sets that requires a separate OpenShift Container Platform cluster subscription. This means that to fully utilize OpenShift AI, you will need both an OpenShift AI entitlement and an active OpenShift Container Platform cluster subscription.

In summary:

- RHEL AI can be used with or without an RHOAI subscription

- OpenShift AI requires both an RHOAI entitlement and an active OpenShift Container Platform cluster subscription.


==  RHEL AI


RHEL AI is designed for open source generative AI model fine tuning and inference. 

 . Provides a simplified approach to get started with *generative AI* using open source AI large language models.
 . Makes Generative AI accessible to developers and domain experts with little data science expertise.
 . Provides the ability to do training & inference on discrete server deployments.

More details are available in the RHEL AI on AWS section.

[WARNING]
Red Hat Enterprise Linux for AI (RHEL AI) supports both custom large language models (LLMs) brought by customers and IBM's Granite family of AI models. While you can use your own LLMs, RHEL AI is specifically optimized to work best with IBM's offerings. The Granite models are open source, enterprise-grade solutions designed for businesses, and they come with an added benefit: they are indemnified against generating copyrighted text. As of now, only the unmodified Granite starter model, which can be downloaded from the Red Hat Registry, is indemnified under this policy. For other models or customizations, it's essential to consult with IBM and Red Hat for specific terms and conditions.


'''

== Red Hat OpenShift AI

RHOAI is a fully functional MLOPs platform which is capable of providing life cycle management for both *predictive AI* and *generative AI* solutions.

 . Provides support for both generative and predictive AI models with a BYOM approach.
 . Includes framework to manage distributed compute, collaborative workflows, model serving and monitoring.
 . Offers enterprise grade machine learning operations platform (MLOps) capabilities while providing a consistent engineering experience across hybrid-clouds.
 . Includes Red Hat Enterprise Linux AI entitlements.


'''



=== Summary:

Depending on an organization's maturity in AI model powered application development. Red Hat AI provides both an out the box Generative AI model product with RHEL AI which scales to integrate with OpenShift AI to provide the full MLOps platform for multi-model AI lifecycle management.

 * *RHEL AI* excels as a getting started solution for low AI maturity organizations seeking to advance in their AI adoption journey by customizing models through fine-tuning using internal data, or who wish to keep internal data private without dedicated data scientists or MLOPs engineers.

 * *OpenShift AI* focuses on Empowering businesses to manage their AI model lifecycle effectively, transitioning from experimentation to production. From data ingestion and preparation for AI model training and inference through operationalizing the entire lifecycle of enterprise multi-AI model application development all the way through AI model monitoring and maintenance in production.


In this course, we will primarily discuss deploying Red Hat AI services on Amazon Web Services (AWS). However, it's important to note that both RHEL AI and OpenShift AI are versatile solutions capable of being deployed across various cloud providers and on-premises environments. This includes private or air-gapped setups, which will be referred to as "Private AI" moving forward. While the focus is on AWS in this course, the concepts and techniques learned can be applied to other deployment scenarios as well.