= OpenShift and OpenShift AI

[NOTE]
This entire page should be hidden

=== OpenShift AI on AWS

For ROSA Classic, get a subscription through the AWS Marketplace.

 * Install the Red Hat OpenShift AI Add-on.
 * Access the OpenShift AI dashboard.
 * Optionally, enable graphics processing units (GPUs) in OpenShift AI to ensure that your data scientists can use compute-heavy workloads in their models.


For an existing ROSA Classic cluster, you can get the compute node instance type by using this command:

rosa list machinepools --cluster=cluster-name

=== AI Model Life Cycle 

FY24 saw customers moving gen AI projects out of Proof of Concepts, largely performed using *hyperscaler services*, into Pilot and Production. In that move, customers realized the generalized hyperscaler AI services may not provide enough value to the business and had *highly variable and unpredictable costs*. 

During this time, the quantity and quality of viable open and permissively licensed models (ie Llama, Mistral) greatly increased, leading customers to explore private deployments of gen AI vs using hyperscaler services. 

Ability to support customer owned systems across hybrid cloud footprints for container, virtualization and AI workloads on a single enterprise platform (OpenShift), 

=== just holding this information here - delete


Cloud Providers incentive is to make it easy to consume more resources

ways they do this...democratize access to mathethematics - why haven't we made this easier to understand.

clever to make complex problems simple.

collaboration across teams - incitives to unite to provide an unified system that is easy to maintain. 

hardware cost moving back to on-prem.

run a bunch of experiments at the same time.
- automatic machine learning tooling, test multiple models against your problem statement.

really easy to consume more resources...

easy to build complete systems, make bills easier to undertsand.

model marketplace - off the shelf models from cloud vendors.
easier to deploy something that is hard to manage.

                                                                                                                                   

== TDB Above



