= OpenShift (AI) on AWS

== Deployment Options

There two types of installation options for Red Hat OpenShift AI self-managed and Red Hat OpenShift AI cloud service.  This course will focus on the Cloud Service, Red Hat Managed installations for AWS.
There is an exception, a hybrid approach that could yield substantial benefits to customers that will be briedly discussed. 

https://access.redhat.com/articles/rhoai-supported-configs[For more information, this article lists the Red Hat OpenShift AI (RHOAI) offerings (Self-Managed and Cloud Service), the RHOAI components, their current support phase, and their compatibility with the underlying platforms.]


=== Amazon Web Services (AWS)

There are managed offerings of Red Hat OpenShift AI as a managed cloud service add-on for AWS.  

==== OpenShift Dedicated with a Customer Cloud Subscription on Amazon Web Services 
OpenShift Dedicated is a complete OpenShift Container Platform cluster provided as a cloud service, configured for high availability, and *dedicated* to a single customer. OpenShift Dedicated is professionally managed by Red Hat and hosted on Amazon Web Services (AWS). The Customer Cloud Subscription (CCS) model allows Red Hat to deploy and manage clusters into a customer’s AWS account. 

[NOTE]
While not specifically mentioned in this course, there is also OpenShift decidcated option for Google Cloud Platform (GCP).  This is the only support GCP offering of managed OpenShift / OpenShift AI.

==== Red Hat OpenShift Service on AWS (ROSA Classic)
ROSA is a fully-managed, turnkey application platform that allows you to focus on delivering value to your customers by building and deploying applications. You subscribe to the service directly from your AWS account.

For ROSA Classic, get a subscription through the AWS Marketplace.

==== Red Hat OpenShift Service on AWS (ROSA) with Hosted Control Plane
 
Red Hat OpenShift Service on AWS with hosted control planes (ROSA with HCP) is a fully-managed and jointly supported Red Hat OpenShift offering that combines the power of Red Hat OpenShift, the industry's most comprehensive enterprise Kubernetes platform, and the AWS public cloud. 

Hosting and managing the control plane in a ROSA managed service account provides the most effective and efficient use of customer resources, resulting in significant cost savings, faster provisioning time, improved security posture and increased reliability for ROSA customers. With this, users experience a multitude of benefits, such as:

Hosted control planes provide better cost, faster provisioning time, and security optimizations for managing your workloads. As a result, they are well suited for many use cases, such as:

 . Hosting clusters with specific characteristics.
 . Workload tiering.
 . Flexible upgrades (control planes can be upgraded independently of workers).

[WARNING]
OpenShift AI is not supported on ROSA with HCP as Cloud Manage Service.  However, AI workloads and applications are supported on OpenShift, and OpenShift AI self-managed can be installed by customers on ROSA with HCP.  Install OpenShift AI Self-Managed by installing the Red Hat OpenShift AI Operator and then configuring the Operator to manage standalone components of the product.

This includes support for RHOAI self-managed on managed OpenShift offerings such as OpenShift Dedicated, Red Hat OpenShift Service on AWS (ROSA), ROSA with hosted control planes, and Microsoft Azure Red Hat OpenShift. Currently, RHOAI Self-Managed is not supported on OpenShift running on other architectures (for example: ARM, IBM Power, IBM Z), and on other platforms such as OpenShift Kubernetes Engine, single node OpenShift, and MicroShift.
For a full overview of the RHOAI Self-Managed life cycle and the currently supported releases, 


